[package]
name = "rust-raytracer"
version = "0.1.0"
authors = [
    "ng.guoyou@gmail.com",
    "stacey.ell@gmail.com"
]

[dependencies.time]
git = "http://github.com/rust-lang/time"

[dependencies.rustc-serialize]
rustc-serialize = "0.2.2"
