[package]
name = "rust-raytracer"
version = "0.1.0"
authors = [
    "ng.guoyou@gmail.com",
    "stacey.ell@gmail.com"
]

[dependencies]
num = "*"
num_cpus = "*"
rand = "*"
rustc-serialize = "*"
threadpool = "*"
time = "*"

[dependencies.png]
git = "https://github.com/servo/rust-png"